#!/bin/bash
#SBATCH --partition=H100
##SBATCH --partition=DGX
#SBATCH --account=lade
##SBATCH --nodelist=dgx004
#SBATCH --nodes=1
#SBATCH --time=24:00:00            
#SBATCH --ntasks-per-node=1       
#SBATCH --cpus-per-task=56 #32          
#SBATCH --mem=450G                   
#SBATCH --job-name=test
#SBATCH --gres=gpu:H100:4

#source /u/area/ddoimo/anaconda3/bin/activate ./env_a100
module load cuda/12.8 
export CUDA_HOME=$CUDA_PATH

source /u/area/ddoimo/anaconda3/bin/activate ./env_h100 

export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True" 
export PYTHONUNBUFFERED=1
#export TRANSFORMERS_OFFLINE=1
export HF_HOME=/orfeo/cephfs/scratch/area/ddoimo/models

GPU_NUMBER=$(echo $CUDA_VISIBLE_DEVICES | tr ',' ' ' | wc -w)
WORKERS_PER_RANK=$(( SLURM_CPUS_PER_TASK / GPU_NUMBER ))
#
export OMP_NUM_THREADS=$WORKERS_PER_RANK
export NUMEXPR_MAX_THREADS=$WORKERS_PER_RANK
export OPENBLAS_NUM_THREADS=$WORKERS_PER_RANK   
export MKL_NUM_THREADS=$WORKERS_PER_RANK   

nodes=( $( scontrol show hostnames $SLURM_JOB_NODELIST ) )
head_node=${nodes[0]}
head_node_ip=$(getent hosts "$head_node" | awk '{ print $1 }')

#--negatives_dir results/datasets_negatives/qwen3_600m \
#--measure_baselines \
# --eval_only \
# --distributed_loss \
# --use_lora \
# --lora_rank 128 \
# --lora_alpha 256 \
# --lora_dropout 0.1 \
# --activation_checkpointing \
# --model_name_or_path google/t5gemma-2-270m-270m  \
# --model_name_or_path google/embeddinggemma-300m \
# --model_name_or_path Qwen/Qwen3-Embedding-0.6B \
#benchmark_collate_fn_pretokenized.py \

#
torchrun \
    --nnodes=$SLURM_NTASKS \
    --node-rank=$SLURM_NODEID \
    --nproc-per-node=$GPU_NUMBER \
    --rdzv-id=$SLURM_PROCID \
    --rdzv-backend=c10d \
    --rdzv-endpoint=$head_node:0 \
    train.py \
    --loss_type f2llm \
    --train_subset retrieval \
    --out_filename f2llm_retrieval_f2llm_loss \
    --num_hard_negatives 7 \
    --negatives_dir results/f2llm_tokenized/f2llm-prompt_qwen3-tok \
    --model_name_or_path Qwen/Qwen3-Embedding-0.6B \
    --eval_set mteb_eng_v2_reduced \
    --batch_strategy f2llm_multi \
    --length_strategy truncate \
    --max_seq_len 1024  \
    --attention_dim 256 \
    --num_workers $WORKERS_PER_RANK \
    --per_device_train_batch_size 48 \
    --per_device_eval_batch_size 128 \
    --learning_rate 1e-5 \
    --lr_min_fact 0.01 \
    --warmup_ratio 0.03 \
    --weight_decay 0.01  \
    --num_train_epochs 1 \
    --checkpointing_steps 1 \
    --logging_steps 60 \
    --eval_steps 60 \
    --output_dir "./results/train" \