#!/bin/bash
#SBATCH --partition=H100
##SBATCH --nodelist=dgx004
#SBATCH --account=lade
#SBATCH --nodes=1
#SBATCH --time=8:00:00            
#SBATCH --ntasks-per-node=1       
#SBATCH --cpus-per-task=16
#SBATCH --mem=200G       
#SBATCH --job-name=test
#SBATCH --gres=gpu:H100:1
##SBATCH --gres=gpu:A100:1


env_path=/orfeo/cephfs/scratch/area/ddoimo/open/hidden_pool_embeddings

source /u/area/ddoimo/anaconda3/bin/activate  $env_path/env_h100

# module load cuda/12.8
# source /u/area/ddoimo/anaconda3/bin/activate  $env_path/env_h100


nodes=( $( scontrol show hostnames $SLURM_JOB_NODELIST ) )
nodes_array=($nodes)
head_node=${nodes_array[0]}

GPU_NUMBER=$(echo $CUDA_VISIBLE_DEVICES | tr ',' ' ' | wc -w) 
export HF_HOME=/orfeo/cephfs/scratch/area/ddoimo/models
export PYTHONUNBUFFERED=1


WORKERS_PER_RANK=$(( SLURM_CPUS_PER_TASK / GPU_NUMBER ))
#
export OMP_NUM_THREADS=$WORKERS_PER_RANK
export NUMEXPR_MAX_THREADS=$WORKERS_PER_RANK
export OPENBLAS_NUM_THREADS=$WORKERS_PER_RANK   
export MKL_NUM_THREADS=$WORKERS_PER_RANK  


#python extract_mteb_test_datasets.py  



# torchrun \
#     --nnodes=$SLURM_NTASKS \
#     --node-rank=$SLURM_NODEID \
#     --nproc-per-node=$GPU_NUMBER \
#     --rdzv-id=$SLURM_PROCID \
#     --rdzv-backend=c10d \
#     --rdzv-endpoint=$head_node:0 \

    #--benchmark
    #--model_name_or_path "Qwen/Qwen3-Embedding-0.6B" \
    #--model_name_or_path google/embeddinggemma-300m \


torchrun \
    --nnodes=$SLURM_NTASKS \
    --node-rank=$SLURM_NODEID \
    --nproc-per-node=$GPU_NUMBER \
    --rdzv-id=$SLURM_PROCID \
    --rdzv-backend=c10d \
    --rdzv-endpoint=$head_node:0 \
    eval_model_with_ddp.py  \
    --model_name_or_path Qwen/Qwen3-Embedding-0.6B \
    --benchmark mteb_eng_v2_reduced  \
    --batch_size 8 \
    --max_eval_queries 500000 \
    --evaluate_hidden_states \
    #--task_name ArguAna \




#--model_name_or_path Qwen/Qwen3-Embedding-0.6B \

# torchrun \
#     --nnodes=$SLURM_NTASKS \
#     --node-rank=$SLURM_NODEID \
#     --nproc-per-node=$GPU_NUMBER \
#     --rdzv-id=$SLURM_PROCID \
#     --rdzv-backend=c10d \
#     --rdzv-endpoint=$head_node:0 \
#     eval_model_with_ddp.py  \
#     --model_name_or_path Qwen/Qwen3-Embedding-8B \
#     --benchmark mteb_eng_v2  \
#     --batch_size 16 \
    #--model_name_or_path google/embeddinggemma-300m  \
    #--filename 1gpu \
    #--model_name_or_path Qwen/Qwen3-Embedding-8B \
    #--benchmark mteb_multilingual_v2 \
    #--benchmark mteb_eng_v2  \
    # --model_name_or_path "Qwen/Qwen3-Embedding-0.6B" \
    # --benchmark mteb_multilingual_v2 \

    #--model_name_or_path Qwen/Qwen3-Embedding-0.6B \
 
