#!/bin/bash
#SBATCH --partition=H100
##SBATCH --partition=DGX
#SBATCH --account=lade
##SBATCH --nodelist=dgx004
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=56
#SBATCH --mem=450G
#SBATCH --job-name=test
#SBATCH --gres=gpu:H100:4

module load cuda/12.8
export CUDA_HOME=$CUDA_PATH

source /u/area/ddoimo/anaconda3/bin/activate ./env_f2llm

export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True"
export PYTHONUNBUFFERED=1
export HF_HOME=/orfeo/cephfs/scratch/area/ddoimo/models

GPU_NUMBER=$(echo $CUDA_VISIBLE_DEVICES | tr ',' ' ' | wc -w)
WORKERS_PER_RANK=$(( SLURM_CPUS_PER_TASK / GPU_NUMBER ))

export OMP_NUM_THREADS=$WORKERS_PER_RANK
export NUMEXPR_MAX_THREADS=$WORKERS_PER_RANK
export OPENBLAS_NUM_THREADS=$WORKERS_PER_RANK
export MKL_NUM_THREADS=$WORKERS_PER_RANK

nodes=( $( scontrol show hostnames $SLURM_JOB_NODELIST ) )
head_node=${nodes[0]}
head_node_ip=$(getent hosts "$head_node" | awk '{ print $1 }')

# accelerate launch \
#     --num_machines $SLURM_NTASKS \
#     --machine_rank $SLURM_NODEID \
#     --num_processes $(( SLURM_NTASKS * GPU_NUMBER )) \
#     --main_process_ip $head_node_ip \
#     --main_process_port 29500 \
#     --mixed_precision bf16 \
#     --use_deepspeed \
#     --zero_stage 2 \
#     --gradient_accumulation_steps 1 \
#     --gradient_clipping 1.0 \
#     run.py --config configs/config.json

#--model_path Qwen/Qwen3-Embedding-0.6B \
torchrun \
    --nnodes=$SLURM_NTASKS \
    --node-rank=$SLURM_NODEID \
    --nproc-per-node=$GPU_NUMBER \
    --rdzv-id=$SLURM_PROCID \
    --rdzv-backend=c10d \
    --rdzv-endpoint=$head_node:0 \
    train_f2llm_repro.py \
    --model_path google/t5gemma-2-270m-270m  \
    --experiment_id trial \
    --train_data_path ./f2llm_repro/results/datasets_tokenized/f2llm/f2llm-prompt_t5gemma-2-tok \
    --num_workers $WORKERS_PER_RANK \
    --output_dir ./f2llm_repro/results/train \
    --tb_dir ./f2llm_repro/results/tensorboard \
    --train_batch_size 64 \
    --max_seq_length 1024 \
    --learning_rate 1e-5 \
    --min_lr 1e-7 \
    --weight_decay 0.01 \
    --warmup_steps 500 \
    --train_epochs 1 \
    --log_interval 500 \
    --validation_interval 4000 \
    --test_interval 20000 \
    --num_hard_neg 7 \
    --eval_set mteb_eng_v2_reduced \
    #--measure_baselines \
    #--model_path Qwen/Qwen3-0.6B  \
    #--train_data_path ./f2llm_repro/results/datasets_tokenized/f2llm/qwen3_600m-teacher_f2llm-prompt_qwen3-tok \
