#!/bin/bash
#SBATCH --partition=H100
##SBATCH --partition=DGX
#SBATCH --account=lade
##SBATCH --nodelist=dgx004
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=56
#SBATCH --mem=350G
#SBATCH --job-name=test
#SBATCH --gres=gpu:H100:4

module load cuda/12.8
export CUDA_HOME=$CUDA_PATH

source /u/area/ddoimo/anaconda3/bin/activate ./env_h100

export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True"
export PYTHONUNBUFFERED=1
export HF_HOME=/orfeo/cephfs/scratch/area/ddoimo/models

GPU_NUMBER=$(echo $CUDA_VISIBLE_DEVICES | tr ',' ' ' | wc -w)
WORKERS_PER_RANK=$(( SLURM_CPUS_PER_TASK / GPU_NUMBER ))

export OMP_NUM_THREADS=$WORKERS_PER_RANK
export NUMEXPR_MAX_THREADS=$WORKERS_PER_RANK
export OPENBLAS_NUM_THREADS=$WORKERS_PER_RANK
export MKL_NUM_THREADS=$WORKERS_PER_RANK

nodes=( $( scontrol show hostnames $SLURM_JOB_NODELIST ) )
head_node=${nodes[0]}
head_node_ip=$(getent hosts "$head_node" | awk '{ print $1 }')

torchrun \
    --nnodes=$SLURM_NTASKS \
    --node-rank=$SLURM_NODEID \
    --nproc-per-node=$GPU_NUMBER \
    --rdzv-id=$SLURM_PROCID \
    --rdzv-backend=c10d \
    --rdzv-endpoint=$head_node:0 \
    find_f2llm_false_negatives.py \
    --model_name_or_path Qwen/Qwen3-Embedding-0.6B \
    --input_dir  results/f2llm_data_no_instruct \
    --output_dir results/f2llm_annotated \
    --batch_size 32 \
    --max_length 1024 \
    --top_k 100 \
    #--data_subset bioasq #arguana hotpotqa msmarco
