#!/bin/bash
#SBATCH --partition=H100
##SBATCH --partition=DGX
#SBATCH --account=lade
##SBATCH --nodelist=dgx002
#SBATCH --nodes=1
#SBATCH --time=24:00:00            
#SBATCH --ntasks-per-node=1       
#SBATCH --cpus-per-task=56 #32          
#SBATCH --mem=200G                   
#SBATCH --job-name=test
#SBATCH --gres=gpu:H100:4

#source /u/area/ddoimo/anaconda3/bin/activate ./env_a100
module load cuda/12.8 
export CUDA_HOME=$CUDA_PATH

source /u/area/ddoimo/anaconda3/bin/activate ./env_f2llm

export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True" 
export PYTHONUNBUFFERED=1
#export TRANSFORMERS_OFFLINE=1
export HF_HOME=/orfeo/cephfs/scratch/area/ddoimo/models

GPU_NUMBER=$(echo $CUDA_VISIBLE_DEVICES | tr ',' ' ' | wc -w)
WORKERS_PER_RANK=$(( SLURM_CPUS_PER_TASK / GPU_NUMBER ))
#
export OMP_NUM_THREADS=$WORKERS_PER_RANK
export NUMEXPR_MAX_THREADS=$WORKERS_PER_RANK
export OPENBLAS_NUM_THREADS=$WORKERS_PER_RANK   
export MKL_NUM_THREADS=$WORKERS_PER_RANK   


filepath=./CodeFuse-Embeddings/F2LLM
export PYTHONPATH="${PWD}/CodeFuse-Embeddings:${PYTHONPATH}"
accelerate launch --config_file $filepath/configs/accelerate_config.yaml $filepath/run.py --config $filepath/configs/config.json