#!/bin/bash
#SBATCH --partition=H100
#SBATCH --account=lade
##SBATCH --nodelist=dgx003
#SBATCH --nodes=1
#SBATCH --time=24:00:00            
#SBATCH --ntasks-per-node=1       
#SBATCH --cpus-per-task=16 #32          
#SBATCH --mem=100G  #it is intended per node          
#SBATCH --job-name=test
#SBATCH --gres=gpu:2 #it is intended per node



#source /u/area/ddoimo/anaconda3/bin/activate ./env_amd 
module load cuda/12.6 
export CUDA_HOME=$CUDA_PATH

source /u/area/ddoimo/anaconda3/bin/activate ./env_h100 

export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True" 
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export PYTHONUNBUFFERED=1
#export TRANSFORMERS_OFFLINE=1
export HF_HOME=/orfeo/cephfs/scratch/area/ddoimo/models

nodes=( $( scontrol show hostnames $SLURM_JOB_NODELIST ) )
head_node=${nodes[0]}
head_node_ip=$(getent hosts "$head_node" | awk '{ print $1 }')
GPU_NUMBER=$(echo $CUDA_VISIBLE_DEVICES | tr ',' ' ' | wc -w) 


torchrun \
    --nnodes=$SLURM_NTASKS \
    --node-rank=$SLURM_NODEID \
    --nproc-per-node=$GPU_NUMBER \
    --rdzv-id=$SLURM_PROCID \
    --rdzv-backend=c10d \
    --rdzv-endpoint=$head_node:0 \
   train.py \
    --model_name_or_path google/gemma-3-270m  \
    --distributed_loss \
    --attention_dim 128 \
    --use_lora \
    --lora_rank 128 \
    --lora_alpha 256 \
    --lora_dropout 0.1 \
    --preprocessing_num_workers 16 \
    --per_device_train_batch_size 256 \
    --per_device_eval_batch_size 256 \
    --learning_rate 2e-5 \
    --lr_min_fact 0.1 \
    --warmup_ratio 0.03 \
    --weight_decay 0.1  \
    --num_train_epochs 1 \
    --checkpointing_steps 1 \
    --logging_steps 10 \
    --eval_steps 7 \
    --output_dir "./results/rebuttal/final" \
    --measure_baselines \