# Dataset name -> task type
TASK_TO_TASK_TYPE = {
    # Retrieval — question answering
    "arguana": "Retrieval",
    "squad": "Retrieval",
    "bioasq": "Retrieval",
    "nfcorpus": "Retrieval",
    "miracl": "Retrieval",
    "mr_tydi": "Retrieval",
    # Retrieval — web search
    "paq": "Retrieval",
    "stackexchange": "Retrieval",
    "msmarco": "Retrieval",
    "natural_questions": "Retrieval",
    # Retrieval — NLI / entailment
    "snli": "Retrieval",
    "mnli": "Retrieval",
    "anli": "Retrieval",
    # Retrieval — misc
    "hotpotqa": "Retrieval",
    "fever": "Retrieval",
    "eli5": "Retrieval",
    "fiqa2018": "Retrieval",
    "scifact": "Retrieval",
    "triviaqa": "Retrieval",
    "coliee": "Retrieval",
    "pubmedqa": "Retrieval",
    "s2orc_title_abstract": "Retrieval",
    "s2orc_title_citation": "Retrieval",
    "s2orc_abstract_citation": "Retrieval",
    "amazon_qa": "Retrieval",
    "specter": "Retrieval",
    "xsum": "Retrieval",
    "cnn_dm": "Retrieval",
    "sentence_compression": "Retrieval",
    "qqp": "Retrieval",
    "stackexchange_dup_questions_s2s": "Retrieval",
    "stackexchange_dup_questions_p2p": "Retrieval",
    "stackoverflow_dup_questions": "Retrieval",
    "sts12": "Retrieval",
    "sts22": "Retrieval",
    "sts_benchmark": "Retrieval",
    # Classification
    "amazon_counterfactual": "Classification",
    "amazon_polarity": "Classification",
    "imdb": "Classification",
    "toxic_conversations": "Classification",
    "cola": "Classification",
    # Clustering
    "amazon_reviews": "Clustering",
    "banking77": "Clustering",
    "emotion": "Clustering",
    "mtop_intent": "Clustering",
    "mtop_domain": "Clustering",
    "massive_scenario": "Clustering",
    "massive_intent": "Clustering",
    "tweet_sentiment_extraction": "Clustering",
    "arxiv_clustering_p2p": "Clustering",
    "arxiv_clustering_s2s": "Clustering",
    "biorxiv_clustering_p2p": "Clustering",
    "biorxiv_clustering_s2s": "Clustering",
    "medrxiv_clustering_p2p": "Clustering",
    "medrxiv_clustering_s2s": "Clustering",
    "reddit_clustering_p2p": "Clustering",
    "reddit_clustering_s2s": "Clustering",
    "stackexchange_clustering_p2p": "Clustering",
    "stackexchange_clustering_s2s": "Clustering",
    "twenty_newsgroups": "Clustering",
}

# Dataset name -> prompt
TASK_TO_PROMPT = {
    # Retrieval — question answering
    "arguana": "Given a question, retrieve passages that answer the question.",
    "squad": "Given a question, retrieve passages that answer the question.",
    "bioasq": "Given a question, retrieve passages that answer the question.",
    "nfcorpus": "Given a question, retrieve passages that answer the question.",
    "miracl": "Given a question, retrieve passages that answer the question.",
    "mrtydi": "Given a question, retrieve passages that answer the question.",
    # Retrieval — web search
    "paq": "Given a web search query, retrieve relevant passages that answer the query.",
    "stackexchange": "Given a web search query, retrieve relevant passages that answer the query.",
    "msmarco": "Given a web search query, retrieve relevant passages that answer the query.",
    "natural_questions": "Given a web search query, retrieve relevant passages that answer the query.",
    # Retrieval — NLI / entailment
    "snli": "Given a premise, retrieve hypotheses that are entailed by the premise.",
    "mnli": "Given a premise, retrieve hypotheses that are entailed by the premise.",
    "anli": "Given a premise, retrieve hypotheses that are entailed by the premise.",
    # Retrieval — misc
    "hotpotqa": "Given a multi-hop question, retrieve passages that answer the question.",
    "fever": "Given a claim, retrieve documents that support or refute the claim.",
    "eli5": "Given a question from Reddit ELI5 forum, retrieve passages that answer it.",
    "fiqa2018": "Given a financial question, retrieve passages that answer the question.",
    "scifact": "Given a scientific claim, retrieve passages that support or refute the claim.",
    "triviaqa": "Given a trivia question, retrieve passages that can answer it.",
    "coliee": "Given a legal statement, retrieve articles that support it.",
    "pubmedqa": "Given a question, retrieve paper abstracts from PubMed that can answer it.",
    "s2orc_title_abstract": "Given a paper's title, retrieve the corresponding abstract.",
    "s2orc_title_citation": "Given a paper's title, retrieve papers that cite it.",
    "s2orc_abstract_citation": "Given a paper's abstract, retrieve abstract of papers that cite it.",
    "amazon_qa": "Given a question about a product, retrieve Amazon reviews that can help answer it.",
    "specter": "Given a scientific paper title, retrieve paper titles that are cited by the given paper.",
    "xsum": "Given a news summary, retrieve the original news article.",
    "cnn_dm": "Given a news summary, retrieve the original news article.",
    "sentence_compression": "Given a compressed sentence, retrieve the original sentence before compression.",
    "qqp": "Given a question, retrieve questions that are semantically equivalent.",
    "stackexchange_dup_questions_s2s": "Given a question, retrieve questions that are semantically equivalent.",
    "stackexchange_dup_questions_p2p": "Given a question, retrieve questions that are semantically equivalent.",
    "stackoverflow_dup_questions": "Retrieve duplicate questions from StackOverflow forum.",
    "sts12": "Retrieve semantically similar text.",
    "sts22": "Retrieve semantically similar text.",
    "sts_benchmark": "Retrieve semantically similar text.",
    # Classification
    "amazon_counterfactual": "Classify a given Amazon customer review text as either counterfactual or not counterfactual.",
    "amazon_polarity": "Classify the given Amazon review into positive or negative sentiment.",
    "imdb": "Classify the sentiment expressed in the given movie review text from the IMDB dataset.",
    "toxic_conversations": "Classify the given comments as either toxic or not toxic.",
    "cola": "Classify the given sentence as linguistically acceptable or not acceptable.",
    # Clustering
    "amazon_reviews": "Classify the given Amazon review into its appropriate rating category.",
    "banking77": "Given an online banking query, find the corresponding intents.",
    "emotion": "Classify the emotion expressed in the given Twitter message into one of the six emotions: anger, fear, joy, love, sadness, and surprise.",
    "mtop_intent": "Classify the intent of the given utterance in task-oriented conversation.",
    "mtop_domain": "Classify the intent domain of the given utterance in task-oriented conversation.",
    "massive_scenario": "Given a user utterance as query, find the user scenarios.",
    "massive_intent": "Given a user utterance as query, find the user intents.",
    "tweet_sentiment_extraction": "Classify the sentiment of a given tweet as either positive, negative, or neutral.",
    "arxiv_clustering_p2p": "Identify the main and secondary category of arXiv papers based on the titles and abstracts.",
    "arxiv_clustering_s2s": "Identify the main and secondary category of arXiv papers based on the titles.",
    "biorxiv_clustering_p2p": "Identify the main category of bioRxiv papers based on the titles and abstracts.",
    "biorxiv_clustering_s2s": "Identify the main category of bioRxiv papers based on the titles.",
    "medrxiv_clustering_p2p": "Identify the main category of medRxiv papers based on the titles and abstracts.",
    "medrxiv_clustering_s2s": "Identify the main category of medRxiv papers based on the titles.",
    "reddit_clustering_p2p": "Identify the topic or theme of Reddit posts based on the titles and posts.",
    "reddit_clustering_s2s": "Identify the topic or theme of Reddit posts based on the titles.",
    "stackexchange_clustering_p2p": "Identify the topic or theme of StackExchange posts based on the given paragraphs.",
    "stackexchange_clustering_s2s": "Identify the topic or theme of StackExchange posts based on the titles.",
    "twenty_newsgroups": "Identify the topic or theme of the given news articles.",
}
