[project]
name = "hidden-pool-embeddings"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "torch==2.8.0",
    "torchvision==0.23.0",
    "torchaudio==2.8.0",
    "scikit-learn",
    "numpy",
    "scipy",
    "sentencepiece",
    "datasets==4.6.0",
    "accelerate",
    "peft",
    "tokenizers",
    "transformers==5.2.0",
    "protobuf",
    "evaluate",
    "sentence-transformers==5.2.3",
    "mteb==2.10.1",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchaudio = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.hatch.build.targets.wheel]
packages = ["hidden_pool_embeddings"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
