from tasks.abs_task import AbsTask, TaskMetadata
from datasets import load_dataset, concatenate_datasets, Dataset
import time
import torch.distributed as dist
import pandas as pd
import numpy as np
from tasks.data_helpers import RetrievalRawData
from utils.helpers import return_formatted
from tasks.retrieval_tasks.retrieval_loaders import from_one_hf_dataset


# List of all 174 StackExchange subjects hallucinated
# STACKEXCHANGE_SUBJECTS_HAL = [
#     "3dprinting",
#     "academia",
#     "ai",
#     "android",
#     "anime",
#     "apple",
#     "arduino",
#     "askubuntu",
#     "astronomy",
#     "avp",
#     "aviation",
#     "beer",
#     "bicycles",
#     "bioinformatics",
#     "biology",
#     "bitcoin",
#     "blender",
#     "boardgames",
#     "bricks",
#     "buddhism",
#     "chemistry",
#     "chess",
#     "christianity",
#     "civicrm",
#     "codegolf",
#     "codereview",
#     "coffee",
#     "cogsci",
#     "computergraphics",
#     "conlang",
#     "cooking",
#     "craftcms",
#     "crafts",
#     "crypto",
#     "cs",
#     "cseducators",
#     "cstheory",
#     "datascience",
#     "dba",
#     "devops",
#     "diy",
#     "drupal",
#     "dsp",
#     "earthscience",
#     "ebooks",
#     "economics",
#     "electronics",
#     "elementaryos",
#     "ell",
#     "emacs",
#     "engineering",
#     "english",
#     "ethereum",
#     "expatriates",
#     "expressionengine",
#     "fitness",
#     "freelancing",
#     "french",
#     "gamedev",
#     "gaming",
#     "gardening",
#     "genealogy",
#     "german",
#     "gis",
#     "graphicdesign",
#     "ham",
#     "hardwarerecs",
#     "health",
#     "hermeneutics",
#     "hin",
#     "history",
#     "hobbyists",
#     "homebrew",
#     "hsm",
#     "hsm-history",
#     "iot",
#     "islam",
#     "italian",
#     "japanese",
#     "joomla",
#     "judaism",
#     "korean",
#     "languagelearning",
#     "latin",
#     "law",
#     "libertarianism",
#     "lifehacks",
#     "linguistics",
#     "literature",
#     "magento",
#     "martialarts",
#     "materials",
#     "mathematica",
#     "math",
#     "matheducators",
#     "mathoverflow",
#     "mechanics",
#     "money",
#     "monero",
#     "movies",
#     "music",
#     "musicfans",
#     "mythology",
#     "networkengineering",
#     "opendata",
#     "opensource",
#     "outdoors",
#     "parenting",
#     "patents",
#     "pets",
#     "philosophy",
#     "philosophy-of-language",
#     "photo",
#     "physics",
#     "pm",
#     "poker",
#     "politics",
#     "portuguese",
#     "productivity",
#     "proofassistants",
#     "psychology",
#     "pt",
#     "puzzling",
#     "quant",
#     "quantumcomputing",
#     "raspberrypi",
#     "retrocomputing",
#     "reverseengineering",
#     "robotics",
#     "rpg",
#     "rus",
#     "russian",
#     "salesforce",
#     "scicomp",
#     "scifi",
#     "security",
#     "sharepoint",
#     "sitecore",
#     "skeptics",
#     "softwareengineering",
#     "solana",
#     "sound",
#     "space",
#     "sports",
#     "sqa",
#     "stackapps",
#     "stats",
#     "stellar",
#     "success",
#     "superuser",
#     "sustainability",
#     "tex",
#     "tezos",
#     "tor",
#     "travel",
#     "tridion",
#     "unix",
#     "ux",
#     "vi",
#     "webapps",
#     "webmasters",
#     "wine",
#     "woodworking",
#     "wordpress",
#     "workplace",
#     "worldbuilding",
#     "writing",
# ]


STACKEXCHANGE_SUBJECTS = [
    "3dprinting",
    "academia",
    "ai",
    "android",
    "anime",
    "apple",
    "arduino",
    "askubuntu",
    "astronomy",
    "aviation",
    "avp",
    "beer",
    "bicycles",
    "bioinformatics",
    "biology",
    "bitcoin",
    "blender",
    "boardgames",
    "bricks",
    "buddhism",
    "cardano",
    "chemistry",
    "chess",
    "chinese",
    "christianity",
    "civicrm",
    "codegolf",
    "codereview",
    "coffee",
    "cogsci",
    "computergraphics",
    "conlang",
    "cooking",
    "craftcms",
    "crafts",
    "crypto",
    "cs",
    "cseducators",
    "cstheory",
    "datascience",
    "dba",
    "devops",
    "diy",
    "drones",
    "drupal",
    "dsp",
    "earthscience",
    "ebooks",
    "economics",
    "electronics",
    "elementaryos",
    "ell",
    "emacs",
    "engineering",
    "english",
    "eosio",
    "esperanto",
    "ethereum",
    "expatriates",
    "expressionengine",
    "fitness",
    "freelancing",
    "french",
    "gamedev",
    "gaming",
    "gardening",
    "genealogy",
    "german",
    "gis",
    "graphicdesign",
    "ham",
    "hardwarerecs",
    "health",
    "hermeneutics",
    "hinduism",
    "history",
    "homebrew",
    "hsm",
    "interpersonal",
    "iot",
    "iota",
    "islam",
    "italian",
    "ja",
    "japanese",
    "joomla",
    "judaism",
    "korean",
    "languagelearning",
    "latin",
    "law",
    "lifehacks",
    "linguistics",
    "literature",
    "magento",
    "martialarts",
    "materials",
    "matheducators",
    "mathematica",
    "mathoverflow",
    "mechanics",
    "meta",
    "moderators",
    "monero",
    "money",
    "movies",
    "music",
    "musicfans",
    "mythology",
    "networkengineering",
    "opendata",
    "opensource",
    "or",
    "outdoors",
    "parenting",
    "patents",
    "pets",
    "philosophy",
    "photo",
    "physics",
    "pm",
    "poker",
    "politics",
    "portuguese",
    "pt",
    "puzzling",
    "quant",
    "quantumcomputing",
    "raspberrypi",
    "retrocomputing",
    "reverseengineering",
    "robotics",
    "rpg",
    "ru",
    "rus",
    "russian",
    "salesforce",
    "scicomp",
    "scifi",
    "security",
    "serverfault",
    "sharepoint",
    "sitecore",
    "skeptics",
    "softwareengineering",
    "softwarerecs",
    "sound",
    "space",
    "spanish",
    "sports",
    "sqa",
    "stackapps",
    "stats",
    "stellar",
    "superuser",
    "sustainability",
    "tex",
    "tezos",
    "tor",
    "travel",
    "tridion",
    "ukrainian",
    "unix",
    "ux",
    "vegetarianism",
    "vi",
    "webapps",
    "webmasters",
    "windowsphone",
    "woodworking",
    "wordpress",
    "workplace",
    "worldbuilding",
    "writers",
]

class StackExchangeRetrieval(AbsTask):
    """StackExchange dataset for retrieval - all 174 subjects concatenated.

    Title+body is combined into a single query field, upvoted_answer is used as positive.
    Loads and concatenates all 174 StackExchange subject subsets.
    """

    language = "en"
    hf_name = "flax-sentence-embeddings/stackexchange_titlebody_best_voted_answer_jsonl"
    hf_subset = None  # Will be set to subtask name when loading specific subjects
    split = "train"
    has_multiple_datasets = False
    query_name = "title_body"  # This field will be created by combining title + body
    positive_name = "upvoted_answer"
    revision = "refs/convert/parquet"
    metadata = TaskMetadata(
        type="Retrieval",
        prompt={
            "query": "Given a question, retrieve answers that best answer the question"
        },
    )
    loader = from_one_hf_dataset
    subtasks = STACKEXCHANGE_SUBJECTS
