#!/bin/bash
#SBATCH --partition=EPYC
##SBATCH --nodelist=dgx001
#SBATCH --account=lade
#SBATCH --nodes=1
#SBATCH --time=24:00:00            
#SBATCH --ntasks-per-node=1       
#SBATCH --cpus-per-task=32  #32          
#SBATCH --mem=100G                   
#SBATCH --job-name=test

source /u/area/ddoimo/anaconda3/bin/activate ../env_a100
# module load cuda/12.8 
# export CUDA_HOME=$CUDA_PATH

# source /u/area/ddoimo/anaconda3/bin/activate ./env_h100 

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export PYTHONUNBUFFERED=1
export HF_HOME=/orfeo/cephfs/scratch/area/ddoimo/models


# Tokenize all F2LLM sources that are in NAME_TO_TASK
# python tokenize_data_qwen.py \
#     --tokenizer_path google/t5gemma-2-270m-270m \
#     --root_dir $HF_HOME/hub/datasets--codefuse-ai--F2LLM/snapshots/c8158be982d16202dda93211c1f7a542159acc3e \
#     --output_dir ./results/datasets_tokenized/f2llm/f2llm-prompt_t5gemma-2-tok \
#     --num_workers $SLURM_CPUS_PER_TASK


python estract_f2llm_prompt_templates.py \
    --root_dir $HF_HOME/hub/datasets--codefuse-ai--F2LLM/snapshots/c8158be982d16202dda93211c1f7a542159acc3e \
    # --tokenizer_path google/t5gemma-2-270m-270m \
    # --output_dir ./results/datasets_tokenized/f2llm/f2llm-prompt_t5gemma-2-tok \
    # --num_workers $SLURM_CPUS_PER_TASK